### ISSUE TITLE
Cannot read property 'reduce' of undefined

### ISSUE THREAD

**Issue by ElijahDD** [JimmyLaurent/cloudflare-scraper#14]
```
TypeError: Cannot read property 'reduce' of undefined
    at tryToSolve (/root/dev/node_modules/hcaptcha-solver/index.js:79:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async solveCaptcha (/root/dev/node_modules/hcaptcha-solver/index.js:112:22)
    at async handleCaptcha (/root/dev/node_modules/cloudflare-scraper/src/handleCaptcha.js:48:7)
    at async fillCookiesJar (/root/dev/node_modules/cloudflare-scraper/src/fillCookiesJar.js:39:7)
    at async handleError (/root/dev/node_modules/cloudflare-scraper/index.js:18:5)
    at async cloudflareScraper (/root/dev/node_modules/cloudflare-scraper/index.js:37:20)
    at async /root/dev/1.js:5:22
```

**Comment by ElijahDD** [comment]
And sometimes 

```
Error: could't find the site key
    at extract (/root/dev/node_modules/cloudflare-scraper/src/utils.js:25:11)
    at handleCaptcha (/root/dev/node_modules/cloudflare-scraper/src/handleCaptcha.js:39:19)
    at fillCookiesJar (/root/dev/node_modules/cloudflare-scraper/src/fillCookiesJar.js:52:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async handleError (/root/dev/node_modules/cloudflare-scraper/index.js:18:5)
    at async cloudflareScraper (/root/dev/node_modules/cloudflare-scraper/index.js:37:20)
    at async main (/root/dev/1.js:9:26)
```

**Comment by KumpelStachu** [comment]
I fixed `Error: could't find the site key` by changing value of:
- `SITE_KEY_REGEXP` to `/sitekey=([^"]+)/` in [handleCaptcha.js:5](https://github.com/JimmyLaurent/cloudflare-scraper/blob/master/src/handleCaptcha.js#L5)
- `waitUntil` to `networkidle2` in [fillCookiesJar.js:33](https://github.com/JimmyLaurent/cloudflare-scraper/blob/master/src/fillCookiesJar.js#L33)

**Comment by andress134** [comment]
> I fixed `Error: could't find the site key` by changing value of:
> 
> * `SITE_KEY_REGEXP` to `/sitekey=([^"]+)/` in [handleCaptcha.js:5](https://github.com/JimmyLaurent/cloudflare-scraper/blob/master/src/handleCaptcha.js#L5)
> * `waitUntil` to `networkidle2` in [fillCookiesJar.js:33](https://github.com/JimmyLaurent/cloudflare-scraper/blob/master/src/fillCookiesJar.js#L33)

Cloudflare has updated again the new challenge
