### ISSUE TITLE
Error: timeout on just a moment

### ISSUE THREAD

**Issue by coinproduct** [JimmyLaurent/cloudflare-scraper#20]
any ideas?

**Comment by tpartee** [comment]
Can confirm this issue.

NOTE: According to NPM when installing this package (v1.0.7) the request package is deprecated, which may be the cause of this issue to begin with, perhaps?

```
ec2-user@canisminor:/www/imgur/script/maint$ node cf-test.js
Error: timeout on just a moment
    at fillCookiesJar (/www/imgur/script/maint/node_modules/cloudflare-scraper/src/fillCookiesJar.js:48:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async handleError (/www/imgur/script/maint/node_modules/cloudflare-scraper/index.js:18:5)
    at async cloudflareScraper (/www/imgur/script/maint/node_modules/cloudflare-scraper/index.js:37:20)
    at async /www/imgur/script/maint/cf-test.js:5:22
```

**Comment by aat-antoine** [comment]
I got same error. Is there a workaround ?

**Comment by coinproduct** [comment]
Contact me on telegram teledeniz i might be able to help

**Comment by thiagomorello** [comment]
got same error, any ideas?

**Comment by RamBoFe** [comment]
Perhaps this would come from the user agent used. Are you doing your tests from linux ? If so, I would advise you to use the windows user agent by commenting out the lines of the getUseragent () function in the _utils.js_ file as follows and testing again :

```javascript
function getUserAgent() {
  // const { platform } = process;
  // if (platform === 'darwin') {
  //   return USER_AGENT_MAC;
  // }
  // if (platform === 'win32') {
    return USER_AGENT_WINDOWS;
  // }
  // return USER_AGENT_LINUX;
}
```

**Comment by johann-taberlet** [comment]
https://github.com/JimmyLaurent/torrent-search-api/issues/117#issuecomment-812590408

**Comment by juliodlcz3** [comment]
Hi everyone, I am having the same error after using cloudflare-scrape around thrree-four months:

2021-05-07T22:25:49.624567+00:00 app[worker.1]: Error: timeout on just a moment
2021-05-07T22:25:49.624591+00:00 app[worker.1]: at fillCookiesJar (/app/node_modules/cloudflare-scraper/src/fillCookiesJar.js:48:17)
2021-05-07T22:25:49.624596+00:00 app[worker.1]: at runMicrotasks (<anonymous>)
2021-05-07T22:25:49.624597+00:00 app[worker.1]: at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-05-07T22:25:49.624597+00:00 app[worker.1]: at async handleError (/app/node_modules/cloudflare-scraper/index.js:18:5)
2021-05-07T22:25:49.624597+00:00 app[worker.1]: at async cloudflareScraper (/app/node_modules/cloudflare-scraper/index.js:37:20)
2021-05-07T22:25:49.624598+00:00 app[worker.1]: at async Timeout.init2 [as _onTimeout] (/app/mybot.js:2412:30)

Anyone else is getting this error nowdays?
