### ISSUE TITLE
Error: could't find the site key

### ISSUE THREAD

**Issue by juliodlcz3** [JimmyLaurent/cloudflare-scraper#28]
Hi, I have been using cloudflare-scraper for around three-four months, with a forked repository to change the linux agent user, but the last week has started to failing with the next error:

2021-05-10T17:44:49.403793+00:00 app[worker.1]: Error: could't find the site key
2021-05-10T17:44:49.403805+00:00 app[worker.1]: at extract (/app/node_modules/cloudflare-scraper/src/utils.js:25:11)
2021-05-10T17:44:49.403806+00:00 app[worker.1]: at handleCaptcha (/app/node_modules/cloudflare-scraper/src/handleCaptcha.js:39:19)
2021-05-10T17:44:49.403806+00:00 app[worker.1]: at fillCookiesJar (/app/node_modules/cloudflare-scraper/src/fillCookiesJar.js:52:15)

As you can see I am using It through heroku service, and eventually works fine since my computer but no through heroku, even after restart the application.

It would be the problem that cloudflare ban de ip's from heroku servers?, there is some moments than It works from my computer and anothers times that not.

I really appreciate your response.

**Comment by GhyslainBruno** [comment]
It started happening to me since this morning, I don't have many info about it for the moment, but I think this needs attention of @JimmyLaurent, as maybe Cloudflare has found a way to block the scraper used by this library :-/

**Comment by GhyslainBruno** [comment]
I just found this [PR](https://github.com/JimmyLaurent/cloudflare-scraper) and I thought this would fix this issue, but apparently it doesn't :-( 

At least, it gives some info about how to fix it ! Thanks to @KumpelStachu

**Comment by RamBoFe** [comment]
Same problem for about 2 weeks.  From my development computer as well as my hosting server, it no longer works.

**Comment by DanielMedina114** [comment]
You have to change the line 5 from handleCaptcha.js from:

const SITE_KEY_REGEXP = /sitekey="([^"]+)/;

to:

const SITE_KEY_REGEXP = /vc" value="([^"]+)/;const SITE_KEY_REGEXP = /vc" value="([^"]+)/;

Now the error is missing because the key has been found. 

PD: I have no idea if more changes have to be made for bypassing the hCaptcha.
