### ISSUE TITLE
Cannot destructure property 'body' of 'error.response' as it is undefined

### ISSUE THREAD

**Issue by ElijahDD** [JimmyLaurent/cloudflare-scraper#6]
Sometimes catch this error when use proxy
```
TypeError: Cannot destructure property 'body' of 'error.response' as it is undefined.
    at isCloudflareIUAMError (/root/js/node_modules/cloudflare-scraper/index.js:8:11)
    at handleError (/root/js/node_modules/cloudflare-scraper/index.js:13:7)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async cloudflareScraper (/root/js/node_modules/cloudflare-scraper/index.js:34:20)
    at async /root/js/parse/test.js:10:32
```

**Comment by JimmyLaurent** [comment]
I fixed it, upgrade to 1.0.2.
