### ISSUE TITLE
ReferenceError: commonArgs is not defined

### ISSUE THREAD

**Issue by ElijahDD** [JimmyLaurent/cloudflare-scraper#7]
```
const response = await cloudflareScraper.get({
            url: url,
            proxy: 'http://127.0.0.1:8888',
            headers: {
                'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36'
            }
        });
```

```
ReferenceError: commonArgs is not defined
    at createBrowser (/root/js/node_modules/cloudflare-scraper/src/createBrowser.js:35:5)
    at fillCookiesJar (/root/js/node_modules/cloudflare-scraper/src/fillCookiesJar.js:28:25)
    at handleError (/root/js/node_modules/cloudflare-scraper/index.js:18:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async cloudflareScraper (/root/js/node_modules/cloudflare-scraper/index.js:37:20)
    at async main (/root/js/dev2.js:9:26)
```

**Comment by JimmyLaurent** [comment]
Thanks, it's fixed in 1.0.4.
